name: tudatpy-docs
channels:
  - conda-forge
  - tudat-team
dependencies:
  # All standard tudat-bundle deps are needed for sphinx-documentation for tudatpy.
  - python=3.8
  - numpy
  - pytest
  - matplotlib # for tudat.plotting
  - basemap # for tudat.plotting
  # Other doc related
  - jinja2
  - yaml
  - cmake
  - pydantic
  - numpydoc
  - tudat
  - tudat-resources
  - cspice-cmake
  - sofa-cmake
  - python
  - eigen
  - pybind11
  - compilers
  - pip
  - pip:
     - nbsphinx
     - sphinxcontrib-napoleon
     - sphinx_rtd_theme
     - sphinxcontrib-fulltoc
     - sphinxcontrib-bibtex
     - furo
